# ---------------------------------------------------------
# CORE NETWORK SETTINGS (Moved to top for safety)
# ---------------------------------------------------------
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

# ---------------------------------------------------------
# BASIC SETTINGS
# ---------------------------------------------------------
replicaCount: 1
image:
  repository: 630019796862.dkr.ecr.eu-central-1.amazonaws.com/retail-vadim-store-orders
  pullPolicy: Always
  tag: "latest"
imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
metrics:
  enabled: false

# ---------------------------------------------------------
# APPLICATION CONFIG
# ---------------------------------------------------------
app:
  persistence:
    provider: 'postgresql'
    endpoint: 'orders-postgresql'
    database: 'orders_db'
    secret:
      create: true
      name: orders-db-secret
      username: "orders_user"
      password: "orders_password"
  messaging:
    provider: 'rabbitmq'
    rabbitmq:
      addresses:
        - "orders-rabbitmq:5672"
      secret:
        create: true
        name: orders-rabbitmq-secret
        username: "user"
        password: "password"

# ---------------------------------------------------------
# INFRASTRUCTURE CONTAINERS
# ---------------------------------------------------------
postgresql:
  create: true
  image:
    repository: public.ecr.aws/docker/library/postgres
    pullPolicy: IfNotPresent
    tag: "13"
  service:
    type: ClusterIP
    port: 5432
  persistentVolume:
    enabled: true
    storageClass: "retail-vadim-gp2"
    size: 8Gi

rabbitmq:
  create: true
  image:
    repository: public.ecr.aws/docker/library/rabbitmq
    pullPolicy: IfNotPresent
    tag: "3.8-management"
  service:
    type: ClusterIP
    amqp:
      port: 5672
    http:
      port: 15672
  persistentVolume:
    enabled: true
    storageClass: "retail-vadim-gp2"
    size: 8Gi

securityGroups:
  create: false
  securityGroupIds: []

opentelemetry:
  enabled: false
  instrumentation: ""

podDisruptionBudget:
  enabled: false
  minAvailable: 2
  maxUnavailable: 1

configMap:
  create: true
  name: ""
