replicaCount: 1
image:
  repository: 630019796862.dkr.ecr.eu-central-1.amazonaws.com/retail-vadim-store-orders
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi

autoscaling:
  enabled: false

# 1. APP CONFIGURATION
app:
  persistence:
    provider: 'postgres'  # Use Real DB
  messaging:
    provider: 'rabbitmq'  # Use Real Messaging

# 2. POSTGRESQL CONFIGURATION
postgresql:
  create: true
  image:
    repository: public.ecr.aws/docker/library/postgres
    tag: "13.2"
  primary:
    persistence:
      enabled: true
      storageClass: "retail-vadim-gp2"
      size: 8Gi
  auth:
    username: orders
    password: "orders-password"
    database: orders

# 3. RABBITMQ CONFIGURATION
rabbitmq:
  create: true
  image:
    repository: public.ecr.aws/bitnami/rabbitmq
    tag: "3.8"
  persistence:
    enabled: true
    storageClass: "retail-vadim-gp2"
    size: 8Gi
  auth:
    username: user
    password: "password"

securityGroups:
  create: false
  securityGroupIds: []
