replicaCount: 1

image:
  repository: 630019796862.dkr.ecr.eu-central-1.amazonaws.com/retail-vadim-store-catalog
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 256m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []

metrics:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"

configMap:
  create: true
  name: ""

# 1. ROOT LEVEL: This fills the ConfigMap ArgoCD is showing
persistence:
  provider: "mysql"
  endpoint: "catalog-mysql:3306"
  dbName: "catalog"      # <--- ADD THIS LINE HERE

# 2. APP LEVEL: This ensures the Pod stays healthy
app:
  env:
    - name: DB_ENDPOINT
      value: "catalog-mysql:3306"
    - name: DB_PASSWORD
      value: "my-secret-pw"
    - name: DB_USER
      value: "catalog_user"
    - name: DB_NAME
      value: "catalog"
    - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
      value: "mysql"
persistence:
  provider: mysql
  endpoint: "catalog-mysql:3306"
  dbName: "catalog"

mysql:
  create: true
  rootPassword: "my-secret-pw"
  mysqlUser: "catalog_user"
  mysqlPassword: "my-secret-pw"
  mysqlDatabase: "catalog"
  image:
    repository: public.ecr.aws/docker/library/mysql
    pullPolicy: IfNotPresent
    tag: "8.0"
  service:
    type: ClusterIP
    port: 3306
  persistentVolume:
    enabled: true
    storageClass: "retail-vadim-gp2"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

securityGroups:
  create: false
  securityGroupIds: []

opentelemetry:
  enabled: false
  instrumentation: ""

podDisruptionBudget:
  enabled: false
  minAvailable: 2
  maxUnavailable: 1
