# Default values for checkout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  # FIX 1: Point to your Private ECR
  repository: 630019796862.dkr.ecr.eu-central-1.amazonaws.com/retail-vadim-store-checkout
  pullPolicy: Always
  # FIX 2: Use the tag that exists in your registry
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []

metrics:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'

configMap:
  create: true
  name:

app:
  persistence:
    # FIX 3: Tell the App to use Redis (not memory)
    provider: 'redis'
    redis:
      endpoint: ''
  endpoints:
    orders: http://retail-store-orders:80

# FIX 4: Enable Redis and Configure Storage
redis:
  create: true
  image:
    repository: public.ecr.aws/docker/library/redis
    pullPolicy: IfNotPresent
    tag: "6.0-alpine"
  service:
    type: ClusterIP
    port: 6379
  
  # Add Persistence Block (Matching your Catalog/MySQL pattern)
  persistentVolume:
    enabled: true
    storageClass: "retail-vadim-gp2"
    size: 8Gi
    accessModes:
      - ReadWriteOnce

  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

securityGroups:
  create: false
  securityGroupIds: []

opentelemetry:
  enabled: false
  instrumentation: ''

podDisruptionBudget:
  enabled: false
  minAvailable: 2
  maxUnavailable: 1
